import { Metadata } from "next";
import MainProducts from "../_components/MainProducts/MainProducts";



export const metadata: Metadata = {
  title: "product page",
  description: "Generated by create next app",
};



export default function page() {



  return <>


    <div className="container py-8">
      <MainProducts />
    </div>



  </>
}
